'use client';
import {storeRequest} from '@/lib/supabase-browser';
import { useLanguage } from '../i18n';
import {useEffect,useState} from 'react';
import Frame from '../frame';
import {Choice} from '@/components/choice';
import {products} from '../catalog';
export default function Page(){const {t,locale}=useLanguage();const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[rating,setRating]=useState('5'),[product,setProduct]=useState('整體體驗'),[busy,setBusy]=useState(false);function load(){storeRequest().then(r=>r.json()).then((d:any)=>d.error?setMessage(d.error):setData(d)).catch(()=>setMessage('載入失敗，請重試。'))}useEffect(load,[]);async function post(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget,f=new FormData(form);try{const r=await storeRequest({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'review',name:f.get('name'),content:f.get('content'),product:products.find(p=>p.name===product)?.id||'all',rating:Number(rating)})});const d:any=await r.json();if(!r.ok)throw Error(d.error);form.reset();setMessage('留言已發表。');load()}catch(e){setMessage(e instanceof Error?e.message:'發表失敗。')}finally{setBusy(false)}}return <Frame title={t("香友留聲")} kicker="STORIES & REVIEWS"><p>{t("分享你的選香想法、使用心得，或對 Hoa 的建議。此區為會員自由留言，未標示為已購買評價。")}</p>{data?.configured===false&&<p role="status">{t("會員服務尚未啟用，請稍後再試。")}</p>}<div className="grid2"><section>{data?.reviews.length?data.reviews.map((r:any)=><article className="panel" key={r.id}><div className="row"><strong>{r.name}</strong><span style={{color:'#c8ab73'}} aria-label={r.rating+' '+t('星')}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span></div><p>{r.content}</p><small className="muted">{t(products.find(p=>p.id===r.product)?.name||'整體體驗')} · {new Date(r.created).toLocaleDateString(locale==='vi'?'vi-VN':'zh-TW')}<br/>{t("會員留言 · 未驗證購買")}</small></article>):<div className="panel"><h3>{t(data?'第一縷分享，等你留下。':'載入留言中…')}</h3><p>{t("目前沒有示範評價或虛構星等。")}</p><button onClick={load}>{t("重新載入")}</button></div>}</section><form className="panel" onSubmit={post}><h3>{t("留下你的心意")}</h3><label htmlFor="nickname">{t("公開暱稱")}</label><input id="nickname" name="name" required maxLength={40}/><label>{t("分享主題")}</label><Choice value={product} onChange={setProduct} options={['整體體驗',...products.map(p=>p.name)]}/><label>{t("評分（1–5 星）")}</label><Choice value={rating} onChange={setRating} options={['5','4','3','2','1']}/><label htmlFor="content">{t("留言")}</label><textarea id="content" name="content" required maxLength={1000}/><p className="muted">{t("暱稱、評分及留言將顯示在此頁，請勿填寫電話、住址或其他私人資料。")}</p>{data?.user?<button className="primary" disabled={busy}>{t(busy?'發表中…':'發表留言')}</button>:<a className="primary" href="/login?returnTo=/community" target="_top">{t("登入後留言")}</a>}<p role="status">{t(message)}</p></form></div></Frame>}

